# Generated by Django 4.2.27 on 2025-12-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentcallback',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['callback_type', 'processed'], name='payment_cal_callbac_d9081c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['transaction_id'], name='payment_cal_transac_e2e678_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'status'], name='payments_sale_id_c6e2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='payments_method_5d17d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='payments_transac_4c44f7_idx'),
        ),
    ]
